import streamlit as st
import requests
import plotly.io as pio

API_URL = "http://localhost:8000/analyze"

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI Data Analyst",
    page_icon="📊",
    layout="wide",
)

st.title("📊 AI Data Analyst Agent")
st.caption("Ask questions about sales data in plain English. The agent generates SQL, queries the database, and returns a chart.")

# ── Session state — persists chat history across re-runs ──────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []

# ── Sidebar with example questions ───────────────────────────────────────────
with st.sidebar:
    st.header("Try these questions")
    example_questions = [
        "Which product had the highest revenue in March?",
        "Show total revenue by product category",
        "What is the monthly revenue trend for 2024?",
        "Which region generated the most sales?",
        "Top 5 products by total quantity sold?",
        "Compare revenue across all 4 regions",
        "Which month had the lowest sales?",
    ]
    for q in example_questions:
        if st.button(q, use_container_width=True, key=q):
            st.session_state.pending_question = q

    st.divider()
    st.caption("Stack: LangGraph · FastAPI · SQLite · Plotly · Streamlit")

# ── Render existing chat history ──────────────────────────────────────────────
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

        if msg["role"] == "assistant":
            # Render chart if present
            if msg.get("chart_json"):
                fig = pio.from_json(msg["chart_json"])
                st.plotly_chart(fig, use_container_width=True)

            # Reasoning steps — collapsed by default
            if msg.get("reasoning"):
                with st.expander("🧠 Reasoning steps"):
                    for i, step in enumerate(msg["reasoning"], 1):
                        st.text(f"Step {i}: {step}")

            # SQL used — collapsed by default
            if msg.get("sql_query"):
                with st.expander("🗄️ SQL generated by agent"):
                    st.code(msg["sql_query"], language="sql")

# ── Handle input (typed or sidebar click) ────────────────────────────────────
question = st.chat_input("Ask anything about your sales data...")

# If user clicked a sidebar example, use that
if "pending_question" in st.session_state:
    question = st.session_state.pop("pending_question")

# ── Process question ──────────────────────────────────────────────────────────
if question:
    # Show user message immediately
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.write(question)

    # Call the backend
    with st.chat_message("assistant"):
        with st.spinner("Agent is thinking — generating SQL, querying database, building chart..."):
            try:
                response = requests.post(
                    API_URL,
                    json={"question": question},
                    timeout=60,
                )
                response.raise_for_status()
                data = response.json()

                # Display answer
                st.write(data["answer"])

                # Display chart
                if data.get("chart_json"):
                    fig = pio.from_json(data["chart_json"])
                    st.plotly_chart(fig, use_container_width=True)

                # Reasoning steps
                with st.expander("🧠 Reasoning steps"):
                    for i, step in enumerate(data["reasoning"], 1):
                        st.text(f"Step {i}: {step}")

                # SQL
                with st.expander("🗄️ SQL generated by agent"):
                    st.code(data["sql_query"], language="sql")

                # Save to history
                st.session_state.messages.append({
                    "role":      "assistant",
                    "content":   data["answer"],
                    "chart_json": data.get("chart_json"),
                    "reasoning": data["reasoning"],
                    "sql_query": data["sql_query"],
                })

            except requests.exceptions.ConnectionError:
                st.error("Cannot connect to backend. Make sure FastAPI is running on port 8000.")
            except requests.exceptions.Timeout:
                st.error("Request timed out. The agent took too long — try a simpler question.")
            except Exception as e:
                st.error(f"Something went wrong: {str(e)}")